/* =============================================
   Paws Adoption - Pet Data
   12 adoptable pets with full details
   ============================================= */

const petsData = [
  // --- DOGS ---
  {
    id: 1,
    name: "Buddy",
    species: "dog",
    breed: "Golden Retriever",
    age: 3,
    ageGroup: "adult",
    size: "large",
    gender: "Male",
    color: "Golden",
    description: "Buddy is a friendly, energetic Golden Retriever who loves nothing more than playing fetch and splashing in puddles. He's great with kids and other dogs, and already knows basic commands like sit, stay, and shake. Buddy is house-trained and crate-trained, making him the perfect addition to an active family.",
    personality: ["Friendly", "Playful", "Good with kids", "House-trained", "Energetic"],
    fee: 200,
    image: "https://picsum.photos/seed/buddy-dog/400/300",
    isFeatured: true
  },
  {
    id: 2,
    name: "Luna",
    species: "dog",
    breed: "Siberian Husky",
    age: 2,
    ageGroup: "adult",
    size: "large",
    gender: "Female",
    color: "Gray & White",
    description: "Luna is a stunning Husky with striking blue eyes and a gentle soul. She's incredibly smart and loves learning new tricks. Luna enjoys long walks, hiking adventures, and will happily howl along to her favorite songs. She'd thrive in an active home with a securely fenced yard.",
    personality: ["Intelligent", "Gentle", "Adventurous", "Vocal", "Loyal"],
    fee: 250,
    image: "https://picsum.photos/seed/luna-dog/400/300",
    isFeatured: true
  },
  {
    id: 3,
    name: "Charlie",
    species: "dog",
    breed: "Beagle",
    age: 1,
    ageGroup: "puppy",
    size: "medium",
    gender: "Male",
    color: "Tricolor (Black, White, Brown)",
    description: "Charlie is a curious and lovable Beagle puppy with an endless sense of adventure. His tail never stops wagging! He's working on his house-training and is highly food-motivated, which makes training a breeze. Charlie would be perfect for a family with a fenced yard where he can explore to his heart's content.",
    personality: ["Curious", "Lovable", "Food-motivated", "Playful", "Sweet"],
    fee: 300,
    image: "https://picsum.photos/seed/charlie-dog/400/300",
    isFeatured: true
  },
  {
    id: 4,
    name: "Daisy",
    species: "dog",
    breed: "Labrador Retriever",
    age: 5,
    ageGroup: "adult",
    size: "large",
    gender: "Female",
    color: "Yellow",
    description: "Daisy is a sweet, calm Labrador who has already raised one family's children and is looking for a peaceful retirement home. She's gentle, patient, and loves nothing more than belly rubs and short walks around the neighborhood. Daisy is fully trained and would do wonderfully in a quiet home with older children or seniors.",
    personality: ["Calm", "Gentle", "Patient", "Sweet", "Loyal"],
    fee: 150,
    image: "https://picsum.photos/seed/daisy-dog/400/300",
    isFeatured: false
  },
  {
    id: 5,
    name: "Rocky",
    species: "dog",
    breed: "Mixed Breed (Terrier mix)",
    age: 4,
    ageGroup: "adult",
    size: "small",
    gender: "Male",
    color: "Brindle",
    description: "Rocky may be small, but he has a huge personality! This little terrier mix is brave, confident, and full of energy. He loves tug-of-war, squeaky toys, and curling up on the couch after a good play session. Rocky would be a wonderful companion for someone living in an apartment or house with a small yard.",
    personality: ["Brave", "Confident", "Energetic", "Affectionate", "Playful"],
    fee: 180,
    image: "https://picsum.photos/seed/rocky-dog/400/300",
    isFeatured: false
  },
  {
    id: 6,
    name: "Bailey",
    species: "dog",
    breed: "Cocker Spaniel",
    age: 8,
    ageGroup: "senior",
    size: "medium",
    gender: "Female",
    color: "Chocolate",
    description: "Bailey is a distinguished senior lady with the sweetest eyes and a calm, grateful demeanor. She spent years in a loving home before her owner had to move into assisted living. Bailey is looking for a quiet, cozy home where she can enjoy leisurely walks, sunny spots on the floor, and all the gentle scratches she deserves.",
    personality: ["Sweet", "Calm", "Gentle", "Grateful", "Quiet"],
    fee: 80,
    image: "https://picsum.photos/seed/bailey-dog/400/300",
    isFeatured: false
  },

  // --- CATS ---
  {
    id: 7,
    name: "Mittens",
    species: "cat",
    breed: "Domestic Shorthair",
    age: 2,
    ageGroup: "adult",
    size: "small",
    gender: "Female",
    color: "Tuxedo (Black & White)",
    description: "Mittens is a dapper tuxedo cat with impeccable manners and a playful spirit. She loves chasing laser pointers, batting at feather toys, and perching on windowsills to watch the birds. Mittens is litter-box trained and would do well in a home with or without other cats. She's a bit shy at first but warms up quickly.",
    personality: ["Playful", "Shy at first", "Independent", "Clean", "Sweet"],
    fee: 100,
    image: "https://picsum.photos/seed/mittens-cat/400/300",
    isFeatured: true
  },
  {
    id: 8,
    name: "Oliver",
    species: "cat",
    breed: "Orange Tabby",
    age: 1,
    ageGroup: "kitten",
    size: "small",
    gender: "Male",
    color: "Orange",
    description: "Oliver is a mischievous orange tabby kitten with endless curiosity and the loudest purr in the shelter. He loves climbing cat trees, pouncing on toy mice, and will follow you around the house just to see what you're doing. Oliver needs a patient adopter who will give him plenty of playtime and enrichment.",
    personality: ["Mischievous", "Curious", "Affectionate", "Playful", "Social"],
    fee: 175,
    image: "https://picsum.photos/seed/oliver-cat/400/300",
    isFeatured: true
  },
  {
    id: 9,
    name: "Whiskers",
    species: "cat",
    breed: "Maine Coon mix",
    age: 6,
    ageGroup: "adult",
    size: "large",
    gender: "Male",
    color: "Brown Tabby",
    description: "Whiskers is a majestic Maine Coon mix with a luxurious coat and a mellow, dignified personality. He enjoys lounging in sunbeams, gentle brushing sessions, and the occasional game of slow-motion fetch. Whiskers would thrive in a calm home where he can be the king of his castle. He gets along well with older children.",
    personality: ["Mellow", "Dignified", "Affectionate", "Quiet", "Gentle"],
    fee: 120,
    image: "https://picsum.photos/seed/whiskers-cat/400/300",
    isFeatured: false
  },
  {
    id: 10,
    name: "Lily",
    species: "cat",
    breed: "Calico",
    age: 4,
    ageGroup: "adult",
    size: "medium",
    gender: "Female",
    color: "Calico (White, Orange, Black)",
    description: "Lily is a stunning calico with a warm, nurturing personality. She was found caring for a litter of orphaned kittens and has the most maternal instincts of any cat we've met. Lily loves head scratches, soft blankets, and will happily keep your lap warm during movie nights. She's the perfect companion for a quiet home.",
    personality: ["Nurturing", "Warm", "Calm", "Affectionate", "Loyal"],
    fee: "Free",
    image: "https://picsum.photos/seed/lily-cat/400/300",
    isFeatured: false
  },
  {
    id: 11,
    name: "Simba",
    species: "cat",
    breed: "Siamese",
    age: 10,
    ageGroup: "senior",
    size: "medium",
    gender: "Male",
    color: "Seal Point",
    description: "Simba is a dignified senior Siamese with striking blue eyes and a voice that demands attention. He loves conversations (he'll meow back at you!), warm laps, and soft blankets. Simba's previous family moved overseas and couldn't take him. He's looking for a loving retirement home where he can spend his golden years being pampered.",
    personality: ["Vocal", "Affectionate", "Chatty", "Loving", "Gentle"],
    fee: 50,
    image: "https://picsum.photos/seed/simba-cat/400/300",
    isFeatured: false
  },

  // --- OTHER PETS ---
  {
    id: 12,
    name: "Thumper",
    species: "other",
    breed: "Holland Lop Rabbit",
    age: 2,
    ageGroup: "adult",
    size: "small",
    gender: "Male",
    color: "White & Gray",
    description: "Thumper is the fluffiest, friendliest Holland Lop rabbit you'll ever meet. He loves hopping around his playpen, munching on fresh hay, and getting gentle head rubs. Thumper is litter-box trained and would make a wonderful pet for someone in an apartment or with limited outdoor space. He comes with his enclosure and supplies.",
    personality: ["Friendly", "Gentle", "Playful", "Curious", "Quiet"],
    fee: 60,
    image: "https://picsum.photos/seed/thumper-bunny/400/300",
    isFeatured: false
  },
  {
    id: 13,
    name: "Sunny",
    species: "other",
    breed: "Cockatiel",
    age: 1,
    ageGroup: "adult",
    size: "small",
    gender: "Male",
    color: "Yellow & Gray",
    description: "Sunny is a cheerful cockatiel who loves whistling tunes, mimicking sounds, and bobbing his head to music. He's hand-tamed and enjoys sitting on shoulders while watching TV. Sunny comes with his cage, toys, and a starter pack of food. He'd be a delightful companion for someone who wants a lively, musical friend.",
    personality: ["Cheerful", "Musical", "Social", "Friendly", "Playful"],
    fee: 90,
    image: "https://picsum.photos/seed/sunny-bird/400/300",
    isFeatured: false
  },
  {
    id: 14,
    name: "Pepper",
    species: "other",
    breed: "Syrian Hamster",
    age: 0.5,
    ageGroup: "adult",
    size: "small",
    gender: "Female",
    color: "Dark Gray",
    description: "Pepper is a tiny, adorable Syrian hamster with a big personality. She loves running on her wheel, stuffing her cheeks with treats, and exploring tunnels in her cage. Pepper is very easy to care for and would make a perfect first pet for a responsible child or anyone wanting a low-maintenance furry friend.",
    personality: ["Active", "Curious", "Adorable", "Easy-going", "Quiet"],
    fee: 25,
    image: "https://picsum.photos/seed/pepper-hamster/400/300",
    isFeatured: false
  }
];
